Repository vtex-apps/store-footer, pull requests merged in 2019-01, with the labels that each got.

#19 Bye pages.json! Welcome store-builder
  CHANGELOG.md
  manifest.json
  pages/pages.json
  react/index.js
  react/package.json
  store/blocks.json
  store/interfaces.json
Labels: breaking-change, enhancement

#23 Fix component responsive behavior
  CHANGELOG.md
  manifest.json
  react/footer.css
  react/index.js
Labels: bug

#24 Improve HTML code quality
  CHANGELOG.md
  manifest.json
  react/index.js
Labels: chore
